### ISSUE TITLE
Error one

### ISSUE THREAD

**Issue by Crystal-Gaming** [philxyz/cityscript#1]
[ERROR] lua/vgui/dmodelpanel.lua:63: bad argument #1 to 'ClientsideModel' (string expected, got nil)
1. ClientsideModel - [C]:-1
   1. SetModel - lua/vgui/dmodelpanel.lua:63
   2. DoClick - gamemodes/cityscript/gamemode/cl_playermenu.lua:248
      1. unknown - lua/vgui/dlabel.lua:218
   
   is not a valid model!

**Comment by Crystal-Gaming** [comment]
[ERROR] gamemodes/cityscript/gamemode/cl_binds.lua:35: attempt to index global 'HiddenButton' (a nil value)
1. unknown - gamemodes/cityscript/gamemode/cl_binds.lua:35

[ERROR] gamemodes/cityscript/gamemode/cl_binds.lua:41: attempt to index global 'HiddenButton' (a nil value)
1. unknown - gamemodes/cityscript/gamemode/cl_binds.lua:41

[ERROR] gamemodes/cityscript/gamemode/cl_binds.lua:35: attempt to index global 'HiddenButton' (a nil value)
1. unknown - gamemodes/cityscript/gamemode/cl_binds.lua:35

[ERROR] gamemodes/cityscript/gamemode/cl_binds.lua:41: attempt to index global 'HiddenButton' (a nil value)
1. unknown - gamemodes/cityscript/gamemode/cl_binds.lua:41

**Comment by philxyz** [comment]
Hi - thanks for the feedback - can you let me know if the other things I fixed are also working? That way I can mark them as closed. Also, what were you trying to do when this error came up?

**Comment by philxyz** [comment]
This sounds like there's something else wrong. Please make sure the list of required addons is installed.
